const fX = b;
(function(c, f) {
    const mF = {
        c: 0x9c7,
        f: 0xdf7,
        g: 'NMJQ',
        h: 'Gn7Q',
        i: 0x14f2,
        j: 'XITC',
        k: '89Hn',
        l: 0x1673,
        m: 0xec2,
        n: 'yxI7',
        o: 0x13b5,
        p: 'wCGK',
        q: 0x8ef,
        r: 0x1511,
        s: 0xc8b,
        t: 0x1835
    },
    fW = b,
    g = c();
    while (!![]) {
        try {
            const h = -parseInt(fW(mF.c, 'IcEg')) / 0x1 * (parseInt(fW(mF.f, mF.g)) / 0x2) + parseInt(fW(0x1929, mF.h)) / 0x3 * (-parseInt(fW(mF.i, mF.j)) / 0x4) + -parseInt(fW(0xe11, mF.k)) / 0x5 + -parseInt(fW(mF.l, 'd%lH')) / 0x6 * (-parseInt(fW(mF.m, mF.n)) / 0x7) + -parseInt(fW(mF.o, mF.p)) / 0x8 + -parseInt(fW(mF.q, '9rQu')) / 0x9 * (-parseInt(fW(mF.r, '7NO9')) / 0xa) + parseInt(fW(mF.s, 'Mmsl')) / 0xb * (parseInt(fW(mF.t, 'n7E3')) / 0xc);
            if (h === f) break;
            else g['push'](g['shift']());
        } catch (i) {
            g['push'](g['shift']());
        }
    }
}(a, 0x1d218));

let cfSocketConnect = null;
try {
    import(fX(0x1b57, 'T3Fv'))[fX(0x1600, 'zs!c')](c => {
        const mG = { c: 'NxG1', f: 'vel(' },
        fY = fX;
        if (c && typeof c[fY(0x6b1, mG.c)] === fY(0x8d2, '*lLT')) cfSocketConnect = c[fY(0x1dc0, mG.f)];
    })[fX(0x9c6, 'yxI7')](() => {});
} catch (d) {}

const Version = fX(0x900, 'dZbH');
let config_JSON, proxyIP = '',
    enableSocks5Proxy = null,
    enableSocks5GlobalProxy = ![],
    mySocks5Account = '',
    parsedSocks5Address = {},
    cachedSocks5Whitelist = null,
    cachedProxyIP,
    cachedProxyResolvedArray,
    cachedProxyArrayIndex = 0x0,
    enableProxyFallback = !![],
    debugLogPrint = ![],
    connProxyWhitelist = [];

function hostMatchesProxyList(c) {
    const mJ = { c: 0xfba, f: '9rQu' },
    mI = { c: 0xa8b, f: 'egod', g: 0x16e1, h: '2#Qk' },
    fZ = fX,
    f = connProxyWhitelist[fZ(0x1ea4, 'XITC')] ? SOCKS5whitelist[fZ(mJ.c, mJ.f)](connProxyWhitelist) : SOCKS5whitelist;
    return f[fZ(0x1095, '6UCx')](g => {
        const g0 = fZ;
        try {
            return new RegExp('^' + String(g)[g0(mI.c, 'vel(')]()[g0(0xa43, mI.f)](/\*/g, '.*') + '$', 'i')[g0(mI.g, mI.h)](c);
        } catch (h) {
            return ![];
        }
    });
}
let nat64Config = '',
    cachedNat64Prefixes = null,
    cachedNat64At = 0x0,
    cachedNat64Src = '',
    networkSettings = null,
    cachedNetworkSettings = null,
    cachedNetworkSettingsAt = 0x0,
    cachedAdminPass = null,
    cachedAdminPassAt = 0x0;
const _CFG_KEY = fX(0xffc, 'ZgMu');
let _cfgRaw = null,
    _cfgRawAt = 0x0;

async function getConfigRaw(c) {
    const mK = { c: 'CeJW', f: 0x16c4 },
    g1 = fX;
    if (_cfgRaw !== null && Date[g1(0x1d80, 'egod')]() - _cfgRawAt < 0x7530) return _cfgRaw;
    try {
        _cfgRaw = c['KV'] && typeof c['KV'][g1(0x14be, mK.c)] === g1(mK.f, '[p9(') ? await c['KV'][g1(0xb3b, 'NMJQ')](_CFG_KEY) : null;
        _cfgRawAt = Date[g1(0xecf, '60r9')]();
    } catch (f) {}
    return _cfgRaw;
}

function putConfig(c, f) {
    const mL = { c: 0x1ee2 },
    g2 = fX;
    return _cfgRaw = f, _cfgRawAt = Date[g2(0x1af6, '9rQu')](), c['KV'][g2(mL.c, 'w(Wr')](_CFG_KEY, f);
}
let cachedWorkerUUID = null,
    cachedWorkerUUIDAt = 0x0,
    savedUsersAuth = null,
    savedUsersAuthAt = 0x0,
    lastCentralSync = 0x0,
    SOCKS5whitelist = [fX(0x17bf, 'wCGK'), fX(0x122b, 'Pt3!'), fX(0x133d, 'yxI7'), fX(0x207, 'rsIZ'), fX(0xa81, 'jODS')],
    PagesstaticPages = fX(0x17e6, 'rsIZ');
globalThis[fX(0x1107, '6UCx')] = Date[fX(0x7ec, '0Ua@')]();
const SESSION_MAX_AGE_MS = 0x5265c00,
    LOGIN_MAX_ATTEMPTS = 0x8,
    LOGIN_WINDOW_MS = 0x927c0,
    LOGIN_BLOCK_MS = 0xdbba0,
    __loginAttempts = new Map(),
    WSearlyDataMaxBytes = 0x8 * 0x400,
    WSearlyDataMaxHeaderLength = Math[fX(0x1d23, 'vel(')](WSearlyDataMaxBytes * 0x4 / 0x3) + 0x4,
    upstreamBatchTargetBytes = 0x40 * 0x400,
    upstreamQueueMaxBytes = 0x20 * 0x400 * 0x400,
    upstreamQueueMaxItems = 0x2000,
    downstreamGrainChunkBytes = 0x40 * 0x400,
    downstreamGrainTailThreshold = 0x200,
    downstreamGrainSilentMs = 0x0,
    TCPconcurrentDialCount = 0x4,
    uuidRegex = /^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-4[0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$/,
    NODE_ADDR_REGEX = /^(\[[\da-fA-F:]+\]|[\d.]+|[a-zA-Z0-9](?:[a-zA-Z0-9-]*[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]*[a-zA-Z0-9])?)*)(?::(\d+))?(?:#(.+))?$/,
    TAAKAA_REPO_RAW = fX(0x1032, '*lLT'),
    TAAKAA_VERSION_URL = TAAKAA_REPO_RAW + fX(0x912, 'wCGK'),
    TAAKAA_WORKER_SRC_FALLBACK = TAAKAA_REPO_RAW + fX(0x27b, '9rQu');

function versionGreater(c, f) {
    const mM = { c: '*lLT', f: 0x14de, g: 0x1c8d, h: 0x1b72, i: 0x272, j: 'b)3q', k: 0x1de2, l: '2#Qk', m: 'M5Ii', n: 0xfd3 },
    g3 = fX,
    g = String(c || '')[g3(0x5da, 'Mmsl')](/^[vV]/,'')[g3(0x1df, mM.c)]('.')[g3(mM.f, '9rQu')](j => parseInt(j, 0xa) || 0x0),
    h = String(f || '')[g3(mM.g, 'dbGg')](/^[vV]/,'')[g3(mM.h, 'n7E3')]('.')[g3(mM.i, mM.j)](j => parseInt(j, 0xa) || 0x0);
    for (let j = 0x0; j < Math[g3(mM.k, mM.l)](g[g3(0x1d2d, mM.m)], h[g3(mM.n, 'Mmsl')]); j++) {
        const k = g[j] || 0x0,
            l = h[j] || 0x0;
        if (k > l) return !![];
        if (k < l) return ![];
    }
    return ![];
}
let cachedAutoKey = null;
const _md5md5Cache = new Map(),
    _sha224Cache = new Map();
let _kvMigratedFlag = ![],
    cachedCfUsage = null,
    cachedCfUsageAt = 0x0;
const _cidrListCache = new Map(),
    taakaaXiWorker = {
        async 'fetch'(f, g, h) {
            const mS = {
                c: 0xf41,
                f: '%oj0',
                g: 0x56b,
                h: 0x14c1,
                i: 'egod',
                j: 0x659,
                k: 0x10b9,
                l: '60r9',
                m: 'Mmsl',
                n: 0x1a49,
                o: 0xff8,
                p: '*lLT',
                q: 0x968,
                r: 0x1556,
                s: 'NMJQ',
                t: 0x1489,
                u: 'b)3q',
                v: 0x15eb,
                w: 'IcEg',
                x: 0x318,
                y: 0xf4,
                z: 'Pt3!',
                A: 0x1d1,
                B: '8Ys%',
                C: 0x1e4,
                D: 0x560,
                E: 0x625,
                F: 'PYt$',
                G: 0x12f8,
                H: 'oeP*',
                I: 0xc33,
                J: 'Gn7Q',
                K: 0x8ad,
                L: '9rQu',
                M: 0x9df,
                N: 'dn8p',
                O: 'jODS',
                P: 0xe6f,
                Q: 0x14cd,
                R: 'oeP*',
                S: 'PSkb',
                T: 0x14bf,
                U: 'ZgMu',
                V: 0x1ebc,
                W: 'w3Tt',
                X: 0x187b,
                Y: 'Gn7Q',
                Z: '*lLT',
                a0: 0x14be,
                a1: 0x2df,
                a2: 0x1e11,
                a3: 'CeJW',
                a4: 0x11b2,
                a5: 0x367,
                a6: 0x6e3,
                a7: 0x1d0f,
                a8: '7NO9',
                a9: 0x1140,
                aa: 0x1cd6,
                ab: 0xb3b,
                ac: 0x47d,
                ad: 'jODS',
                ae: 'oeP*',
                af: 0x18d5,
                ag: 0x40a,
                ah: '6UCx',
                ai: 0x11af,
                aj: 'yxI7',
                ak: 'M5Ii',
                al: 0x9cc,
                am: '$p[^',
                an: 0xc84,
                ao: 0x473,
                ap: 'V#kN',
                aq: 'dZbH',
                ar: 0x481,
                as: 'CeJW',
                at: 0x1991,
                au: 0xef3,
                av: 0xd0e,
                aw: 'T3Fv',
                ax: 0xf3,
                ay: '[]Y1',
                az: 0xa1f,
                aA: 0x145d,
                aB: 'NMJQ',
                aC: 0x177e,
                aD: '89Hn',
                aE: 0xdd3,
                aF: 'PSkb',
                aG: 0x804,
                aH: '[]Y1',
                aI: 0x4b4,
                aJ: 0x10b0,
                aK: 0x153a,
                aL: 'Pt3!',
                aM: 0x522,
                aN: '$BSl',
                aO: 0xca0,
                aP: 'b)3q',
                aQ: 0x199c,
                aR: 0x920,
                aS: '7NO9',
                aT: 0x3f6,
                aU: 0xf9c,
                aV: 0x1053,
                aW: 0x492,
                aX: 0xd97,
                aY: 'mRB^',
                aZ: 0xe2e,
                b0: 0xef6,
                b1: 0xe7a,
                b2: 'dn8p',
                b3: 'vel(',
                b4: 0x673,
                b5: 'dn8p',
                b6: 0xbd2,
                b7: 0x904,
                b8: 'CeJW',
                b9: 0x1a66,
                ba: 'dn8p',
                bb: 0x636,
                bc: '$p[^',
                bd: 0x1918,
                be: '7NO9',
                bf: 0xdee,
                bg: '0Ua@',
                bh: 0x7fc,
                bi: 0x1e5d,
                bj: 'GzjL',
                bk: 0x1986,
                bl: 'IcEg',
                bm: '#sM9',
                bn: 0x1e21,
                bo: 0x1d8c,
                bp: 'XITC',
                bq: 0xca7,
                br: 0x3ee,
                bs: 0x190d,
                bt: 0x1bd1,
                bu: 0xac9,
                bv: 0x1ba8,
                bw: 0x1423,
                bx: 0xc95,
                by: 'egod',
                bz: 0x2c9,
                bA: 'zs!c',
                bB: '5M6D',
                bC: 0x1116,
                bD: 'b)3q',
                bE: 0x1ce9,
                bF: 0x4f7,
                bG: 'C2T0',
                bH: 'wCGK',
                bI: 0x1776,
                bJ: 0x14bb,
                bK: 0x474,
                bL: 0xdaa,
                bM: 0x863,
                bN: '2#Qk',
                bO: '89Hn',
                bP: 'b)3q',
                bQ: '60r9',
                bR: 0x1b5b,
                bS: 0x5c1,
                bT: 'rsIZ',
                bU: 0x1154,
                bV: 0x672,
                bW: 0x19d5,
                bX: '6UCx',
                bY: 0xcc7,
                bZ: 'jODS',
                c0: 0xdec,
                c1: 'oeP*',
                c2: 0x19c8,
                c3: 'NxG1',
                c4: 0xd5b,
                c5: 0x974,
                c6: 'ZgMu',
                c7: 0x368,
                c8: 'CeJW',
                c9: '$BSl',
                ca: 0xbb5,
                cb: 'dbGg',
                cc: 0xea2,
                cd: 0x3b7,
                ce: '[]Y1',
                cf: 0x184e,
                cg: 'oeP*',
                ch: 0x19e6,
                ci: 0x10fb,
                ck: 0x8ae,
                cl: 0x17e4,
                cm: 'w(Wr',
                cn: 0x624,
                co: 0x218,
                cp: 0xf22,
                cq: 0x15c3,
                cr: 0x260,
                cs: 'XITC',
                ct: 0x15dc,
                cu: 0x1e65,
                cv: 0x1d56,
                cw: 0x1501,
                cx: 0x119a,
                cy: 0x362,
                cz: 0x291,
                cA: 0x456,
                cB: 0xa80,
                cC: '[p9(',
                cD: 0x52a,
                cE: '1qbp',
                cF: '9rQu',
                cG: 0xddc,
                cH: 0x246,
                cI: 'dbGg',
                cJ: 0x12d3,
                cK: 0x1857,
                cL: 0x3ea,
                cM: 0xc11,
                cN: 0x3ad,
                cO: 'NxG1',
                cP: 0x1c2,
                cQ: '7NO9',
                cR: 'XITC',
                cS: 0x111d,
                cT: 'vel(',
                cU: 0x7ca,
                cV: 'mRB^',
                cW: 0x151,
                cX: 0x49a,
                cY: 'mRB^',
                cZ: 'Mmsl',
                d0: 0x1334,
                d1: 0x511,
                d2: 0x17b5,
                d3: '0Ua@',
                d4: 0x1b52,
                d5: 'vel(',
                d6: 0x569,
                d7: 0x4c4,
                d8: 0x9db,
                d9: 0x1589,
                da: 'dbGg',
                db: 0x4d1,
                dc: 'n7E3',
                dd: 0x1118,
                de: 'PYt$',
                df: 'dbGg',
                dg: 0xfca,
                dh: 'jODS',
                di: '5M6D',
                dj: 0x219,
                dk: 0xb48,
                dl: 'dn8p',
                dm: 0x1aef,
                dn: 'oeP*',
                dp: 0x918,
                dq: 0x1493,
                dr: 0x1d94,
                ds: 0xd4f,
                dt: 0xb61,
                du: 0x1a41,
                dv: 0x888,
                dw: 0x1719,
                dx: 0xa25,
                dy: 0x1e81,
                dz: 0xe26,
                dA: 'NMJQ',
                dB: 0x1df,
                dC: '60r9',
                dD: 0x366,
                dE: 0x384,
                dF: 0x1bd8,
                dG: 0x11b2,
                dH: 0x1bbe,
                dI: '#sM9',
                dJ: 0x1d78,
                dK: 0x5ee,
                dL: '89Hn',
                dM: 0x109e,
                dN: 0x15d8,
                dO: 0x1c72,
                dP: 'XITC',
                dQ: 0xf95,
                dR: 'd%lH',
                dS: 0x96d,
                dT: 'vel(',
                dU: 0x17d3,
                dV: 0x12ba,
                dW: 0x4a9,
                dX: 0xa66,
                dY: 0xfc4,
                dZ: 0xabb,
                e0: 'yxI7',
                e1: 0xf6d,
                e2: 'XITC',
                e3: 0x1395,
                e4: 0x11c2,
                e5: 0x10c0,
                e6: 0x369,
                e7: 0x1b4c,
                e8: 0x1275,
                e9: 0xfbb,
                ea: '5M6D',
                eb: 0x1bc1,
                ec: 0x11d7,
                ed: 0x1091,
                ee: 0xb8a,
                ef: 0x13c1,
                eg: 0x1172,
                eh: '2#Qk',
                ei: 0x1f27,
                ej: 0x187d,
                ek: 0xf92,
                el: '8Ys%',
                em: 0x15fa,
                en: 0x191b,
                eo: '8Ys%',
                ep: 0x64e,
                eq: 0xf9d,
                er: 0x192b,
                es: '%oj0',
                et: 0x1111,
                eu: 'V#kN',
                ev: 0x1d56,
                ew: 0x1d67,
                ex: 0x16b6,
                ey: 0xdd6,
                ez: 0x93a,
                eA: 0x15a1,
                eB: '60r9',
                eC: 0x2c3,
                eD: 0x55e,
                eE: 'C2T0',
                eF: 0x21b,
                eG: '6UCx',
                eH: 0x1e23,
                eI: 0x571,
                eJ: 0x109c,
                eK: 0x1a41,
                eL: 0xf70,
                eM: 'dZbH',
                eN: 0x54e,
                eO: '89Hn',
                eP: 0x346,
                eQ: 'dn8p',
                eR: 0x1006,
                eS: 0x1184,
                eT: 0xd26,
                eU: 'dZbH',
                eV: 0xd20,
                eW: '#sM9',
                eX: '*lLT',
                eY: 0x1044,
                eZ: 0xf93,
                f0: 'Gn7Q',
                f1: 'dn8p',
                f2: 0x1acc,
                f3: 0x486,
                f4: 'Pt3!',
                f5: '7NO9',
                f6: 0x1633,
                f7: 0xb53,
                f8: 0x324,
                f9: 'egod',
                fa: 0xc94,
                fb: '$p[^',
                fc: 0x1db0,
                fd: 0x1df1,
                fe: 0x1363,
                ff: 0x143f,
                fg: 'vel(',
                fh: 0x1b25,
                fi: 'n7E3',
                fj: 0x980,
                fk: 0x113d,
                fl: 0xff7,
                fm: 0x7f8,
                fn: 'b)3q',
                fo: 'CeJW',
                fp: 0x1b0b,
                fq: 'egod',
                fr: 0x964,
                fs: '$BSl',
                ft: 0x1325,
                fu: 'NxG1',
                fv: 0x117d,
                fw: 0x183e,
                fx: 0x1160,
                fy: 'w(Wr',
                fz: 0x258,
                fA: 'Mmsl',
                fB: 'Pt3!',
                fC: 0x8d0,
                fD: 0x4cb,
                fE: '*lLT',
                fF: 'NMJQ',
                fG: 0x1ca4,
                fH: 0x19e0,
                fI: 0x41c,
                fJ: 'M5Ii',
                fK: 0x1e2,
                fL: 'egod',
                fM: 0xd12,
                fN: 'GzjL',
                fO: '6UCx',
                fP: 0x154b,
                fQ: 'dn8p',
                fR: 0x420,
                fS: 0x1cb2,
                fT: '1qbp',
                fU: 0x1031,
                fV: 0x1106,
                mT: 0x1582,
                mU: 0x180e,
                mV: '89Hn',
                mW: 0x1605,
                mX: 0x14ca,
                mY: '*lLT',
                mZ: 0x10ba,
                n0: 'GzjL',
                n1: 0xd9d,
                n2: 0xfab,
                n3: 0x1c88,
                n4: 0x1efa,
                n5: 0x1982,
                n6: 'PSkb',
                n7: 0x1ad,
                n8: 'yxI7',
                n9: 0x1016,
                na: 0x967,
                nb: '[p9(',
                nc: 0x1e34,
                nd: 0x173c,
                ne: 0x1249,
                nf: 0x12cb,
                ng: 0x145c,
                nh: 0x1796,
                ni: 0xc75,
                nj: 'IcEg',
                nk: 'CeJW',
                nl: 0xd4a,
                nm: 0x5f6,
                nn: 0x1a5c,
                no: 'n7E3',
                np: 0xf00,
                nq: 0xa18,
                nr: 0x843,
                ns: 0x1a31,
                nt: 0x19f7,
                nu: 'egod',
                nv: 0x842,
                nw: 0xf7f,
                nx: 0x146c,
                ny: 0x1046,
                nz: 0x1e01,
                nA: 0xe9b,
                nB: 'NxG1',
                nC: 0x11b5,
                nD: 0xa35,
                nE: 'mRB^',
                nF: 0x1f1,
                nG: 'n7E3',
                nH: 0xa96,
                nI: 0x167d,
                nJ: 0x9db,
                nK: 0xc1e,
                nL: 0xb48,
                nM: '5M6D',
                nN: 0x67a,
                nO: 0xdcf,
                nP: 0x14c,
                nQ: 0x15da,
                nR: 'Gn7Q',
                nS: 0x1e83,
                nT: '6UCx',
                nU: 'yxI7',
                nV: '2#Qk',
                nW: 0x1b1c,
                nX: 0x1d35,
                nY: 'M5Ii',
                nZ: 0x14ab,
                o0: 'egod',
                o1: 0x1a4b,
                o2: 'dbGg',
                o3: '6UCx',
                o4: 0x1302,
                o5: '89Hn',
                o6: 0x10c4,
                o7: 0xa87,
                o8: 'rsIZ',
                o9: 0x1728,
                oa: '6UCx',
                ob: 0x305,
                oc: 0x7a5,
                od: 'zs!c',
                oe: '$BSl',
                of: 0xd04,
                og: 0x779,
                oh: 0x15bd,
                oi: 0xaa3,
                oj: 0x823,
                ok: 0x1478,
                ol: 'dn8p',
                om: 'dZbH',
                on: '%oj0',
                oo: 0x1ede,
                op: 0xba1,
                oq: 0x407,
                or: '60r9',
                os: 0x640,
                ot: 'NxG1',
                ou: '60r9',
                ov: 0x2f5,
                ow: 0xa1a,
                ox: 'oeP*',
                oy: 0x1bd0,
                oz: 0x1f8,
                oA: 0x5aa,
                oB: 'NMJQ',
                oC: 0x1ed0,
                oD: 0x854,
                oE: 0x999,
                oF: 0x403,
                oG: 0x1c81,
                oH: 'NMJQ',
                oI: 0x168f,
                oJ: 'PSkb',
                oK: 'd%lH',
                oL: 'IcEg',
                oM: 0x108,
                oN: '#sM9',
                oO: 0x10a7,
                oP: 0xf66,
                oQ: 0x1273,
                oR: 0x174c,
                oS: 0x1510,
                oT: 0xdeb,
                oU: 'XITC',
                oV: 0x1ecb,
                oW: 'M5Ii',
                oX: 0x1bfa,
                oY: 0x640,
                oZ: 'rsIZ',
                p0: 0x1d7c,
                p1: '89Hn',
                p2: 0x1169,
                p3: 'jODS',
                p4: 0x739,
                p5: 0x96d,
                p6: 'vel(',
                p7: 0x16ea,
                p8: 0x1769,
                p9: 0x48f,
                pa: 0x4f4,
                pb: '6UCx',
                pc: 0x136f,
                pd: 0x1791,
                pe: 0x1c75,
                pf: 0x17bb,
                pg: '$BSl',
                ph: 0xd5f,
                pi: 0x14d9,
                pj: 0x17e0,
                pk: 'NMJQ',
                pl: 0x891,
                pm: 'PYt$',
                pn: 0x3eb,
                po: 0x1b2f,
                pp: 0x18b6,
                pq: 0x188e,
                pr: '6UCx',
                ps: 0x15e8,
                pt: 0x7bc,
                pu: 'w(Wr',
                pv: 0x64d,
                pw: '5M6D',
                px: 0x6d9,
                py: 0x7c1,
                pz: '8Ys%',
                pA: 0x1b81,
                pB: 'ZgMu',
                pC: 0xf35,
                pD: 0x1f14,
                pE: 0x16af,
                pF: 0xe54,
                pG: 0x1cf0,
                pH: 0x14b1,
                pI: '9rQu',
                pJ: 0x3e6,
                pK: 0x1ec5,
                pL: '8Ys%',
                pM: 0xd5e,
                pN: 'PYt$',
                pO: 0x1613,
                pP: '9rQu',
                pQ: 0xa83,
                pR: 0x1e08,
                pS: 'CeJW',
                pT: 0x1537,
                pU: 0x25a,
                pV: 'd%lH',
                pW: 0x1d0d,
                pX: 0xdbd,
                pY: 0x573,
                pZ: 'w(Wr',
                q0: 0xcf1,
                q1: 'NxG1',
                q2: 0x30e,
                q3: 'T3Fv',
                q4: 0x1fe,
                q5: 'zs!c',
                q6: 0x1840,
                q7: 0x607,
                q8: 'egod',
                q9: 0x7e2,
                qa: '9rQu',
                qb: 0xdfb,
                qc: '7NO9',
                qd: 'yxI7',
                qe: 0x1b6d,
                qf: 0x180e,
                qg: 0x16bf,
                qh: 'w(Wr',
                qi: 0x16c3,
                qj: 'IcEg',
                qk: 0x10df,
                ql: '89Hn',
                qm: 0x616,
                qn: 'M5Ii',
                qo: 'T3Fv',
                qp: 0x17b9,
                qq: 0xad5,
                qr: 'C2T0',
                qs: 'egod',
                qt: 0xe0f,
                qu: 0x1492,
                qv: 'PYt$',
                qw: 0x1134,
                qx: 0x40e,
                qy: 0x655,
                qz: 'n7E3',
                qA: 0x825,
                qB: 0x104e,
                qC: 0xf5a,
                qD: 0x401,
                qE: 0x1129,
                qF: 'PYt$',
                qG: 0x12b3,
                qH: '89Hn',
                qI: 0x1865,
                qJ: '0Ua@',
                qK: 0x6db,
                qL: '#sM9',
                qM: 'vel(',
                qN: 0x13a9,
                qO: 0x131c,
                qP: 'Pt3!',
                qQ: 'oeP*',
                qR: 'vel(',
                qS: 0x1254,
                qT: 0xd91,
                qU: 'egod',
                qV: 'M5Ii',
                qW: 0x1c8b,
                qX: 0x2f8,
                qY: 0x1042,
                qZ: 0x689,
                r0: '9rQu',
                r1: 0x1cda,
                r2: 'NMJQ',
                r3: 0xc8f,
                r4: '1qbp',
                r5: '5M6D',
                r6: 0xe94,
                r7: 'w(Wr',
                r8: '2#Qk',
                r9: 0x404,
                ra: 'dn8p',
                rb: 0xb2d,
                rc: 0x99e,
                rd: 0x103,
                re: 0x1ec2,
                rf: 0x196b,
                rg: 0x1b0e,
                rh: 0xe43,
                ri: 0x1279,
                rj: 'dbGg',
                rk: 0x16e5,
                rl: 0x5ff,
                rm: 'dbGg',
                rn: 0x125,
                ro: 0x1056,
                rp: 0x5b7,
                rq: 0x1546,
                rr: 0x1a97,
                rs: 0x1a0c,
                rt: 0x1352,
                ru: '89Hn',
                rv: 'yxI7',
                rw: 0xa92,
                rx: '6UCx',
                ry: 0x14ec,
                rz: 'GzjL',
                rA: 0x4ea,
                rB: 0x110,
                rC: 'd%lH',
                rD: 'ZgMu',
                rE: 0x437,
                rF: 0x6b9,
                rG: 0xe03,
                rH: '6UCx',
                rI: 'dbGg',
                rJ: 0x1953,
                rK: 0x7e2,
                rL: 0xb15,
                rM: 0x15c6,
                rN: 0x1801,
                rO: 0x1a05,
                rP: 0x1413,
                rQ: 0x1699,
                rR: '$p[^',
                rS: 0x7ec,
                rT: 'Mmsl',
                rU: 0x1a80,
                rV: 0x1e3a,
                rW: '60r9',
                rX: 0x16dc,
                rY: 0x1ef0,
                rZ: '$BSl',
                s0: 0x1183,
                s1: 0x2dd,
                s2: 0xa88,
                s3: 0x4da,
                s4: 'IcEg',
                s5: '8Ys%',
                s6: 0x19ce,
                s7: 0x1bf2,
                s8: 0xef0,
                s9: 'oeP*',
                sa: 0x1d53,
                sb: 0x1052,
                sc: 0x323,
                sd: '%oj0',
                se: 0x746,
                sf: '$p[^',
                sg: 0x39c,
                sh: 0x1bbb,
                si: 0x1b9e,
                sj: '8Ys%',
                sk: 0x437,
                sl: 0x10f3,
                sm: 'vel(',
                sn: 'dbGg',
                so: 0x1d83,
                sp: 'Pt3!',
                sq: 0x178f,
                sr: 'V#kN',
                ss: 0x1d07,
                st: 0x1c45,
                su: 0x1593,
                sv: 0x1aff,
                sw: '*lLT',
                sx: 0x12d9,
                sy: 'mRB^',
                sz: 0x17ee,
                sA: 'vel(',
                sB: 0x11fb,
                sC: 0x443,
                sD: 0x7ee,
                sE: 0x42f,
                sF: 0x7e7,
                sG: 0x1aa3,
                sH: 'vel(',
                sI: 0x666,
                sJ: 0x778,
                sK: 'Gn7Q',
                sL: 0x1afe,
                sM: 0x7cc,
                sN: 'jODS',
                sO: 0x173b,
                sP: '[]Y1',
                sQ: 0x958,
                sR: 0x598,
                sS: 0x1655,
                sT: '[]Y1',
                sU: 0x15b2,
                sV: 0xa20,
                sW: 0x16a6,
                sX: 'XITC',
                sY: 0x4db,
                sZ: 0x8aa,
                t0: 'wCGK',
                t1: 0x225,
                t2: 'rsIZ',
                t3: 0x19de,
                t4: 0x1e92,
                t5: '5M6D',
                t6: 0xf0e,
                t7: '6UCx',
                t8: 'ZgMu',
                t9: 'Pt3!',
                ta: 0x145,
                tb: 0x1bcf,
                tc: 0x1259,
                td: 'w(Wr',
                te: 0x1b43,
                tf: 'vel(',
                tg: 0x197f,
                th: 0xef8,
                ti: 0x546,
                tj: 'V#kN',
                tk: 0x9e9,
                tl: 0x339,
                tm: 'GzjL',
                tn: 0xb95,
                to: 'NMJQ',
                tp: 0x1dd6,
                tq: '6UCx',
                tr: 0x1cf9,
                ts: 0xc69,
                tt: 0x1ea3,
                tu: 0x13a1,
                tv: 0x2f2,
                tw: 'w(Wr',
                tx: 0xfe1,
                ty: 0x1b15,
                tz: 0x15f,
                tA: 0xc44,
                tB: 0xb3c,
                tC: 0xa2c,
                tD: 0xb89,
                tE: 'egod',
                tF: 0x1de6,
                tG: 'Gn7Q',
                tH: 0x1d79,
                tI: 0x1b58,
                tJ: 0xcf6,
                tK: 0x212,
                tL: 0x396,
                tM: 0x874,
                tN: 0x114a,
                tO: 'oeP*',
                tP: 0x1b79,
                tQ: 0x5d7,
                tR: 0x1787,
                tS: 0x1daa,
                tT: 0x1ab5,
                tU: 'egod',
                tV: 0x144c,
                tW: 0x1e9c,
                tX: 'dbGg',
                tY: 0x197b,
                tZ: 0x378,
                u0: 'NxG1',
                u1: 0x1916,
                u2: 0x3a7,
                u3: 0xfb1,
                u4: 'Mmsl',
                u5: 0x1204,
                u6: 'mRB^',
                u7: 0xbdd,
                u8: 'Pt3!',
                u9: 0xc07,
                ua: 'rsIZ',
                ub: 0x15d,
                uc: 'jODS',
                ud: 0x1b18,
                ue: 0x1b78,
                uf: 0x18bf,
                ug: '[p9(',
                uh: 0x128d,
                ui: 0x16a,
                uj: 0x1cf9,
                uk: 0x52b,
                ul: 0x1a8c,
                um: 0x460,
                un: 0x1443,
                uo: 0x1d11,
                up: 0x1f16,
                uq: 0x982,
                ur: 'zs!c',
                us: '*lLT',
                ut: 0xf0,
                uu: 0x1298,
                uv: 'NxG1',
                uw: 0x14e,
                ux: 'Mmsl',
                uy: 0x1593,
                uz: 0x785,
                uA: 0x8f3,
                uB: '6UCx',
                uC: 0x1b0e,
                uD: 0x1023,
                uE: 'NMJQ',
                uF: 0x14a0,
                uG: 0xd29,
                uH: 'Mmsl',
                uI: 0x1aa9,
                uJ: 0x2b4,
                uK: 0x840,
                uL: 'C2T0',
                uM: 'PSkb',
                uN: 0x4b6,
                uO: 0x223,
                uP: 0x97f,
                uQ: 'zs!c',
                uR: 0x993,
                uS: 0x1c3e,
                uT: '%oj0',
                uU: 0x13fe,
                uV: 0x1ce,
                uW: '%oj0',
                uX: 0x666,
                uY: '7NO9',
                uZ: 0x1cea,
                v0: 0x1c7e,
                v1: 0x45f,
                v2: 0x1118,
                v3: '[p9(',
                v4: 0x86b,
                v5: 0x185,
                v6: 0xac0,
                v7: 0x968,
                v8: 0x10a0,
                v9: 0x1d86,
                va: 'Mmsl',
                vb: 0x19ea,
                vc: 'T3Fv',
                vd: 0x1675,
                ve: 0x12cc,
                vf: 'GzjL',
                vg: 0x13d6,
                vh: 'C2T0',
                vi: 'IcEg',
                vj: 0xc60,
                vk: 'PYt$',
                vl: 0x128c,
                vm: 0x108b,
                vn: '60r9',
                vo: 0x10ba,
                vp: 'GzjL',
                vq: 0xf7e,
                vr: 'dn8p',
                vs: 0x103c,
                vt: 'd%lH',
                vu: 0x75e,
                vv: 0x180,
                vw: '#sM9',
                vx: 0x3d5,
                vy: 0xe76,
                vz: '5M6D',
                vA: 'M5Ii',
                vB: 0x1866,
                vC: 0x1f1e,
                vD: 'egod',
                vE: '%oj0',
                vF: 0x591,
                vG: 0x13e0,
                vH: 'Pt3!',
                vI: 'vel(',
                vJ: 'rsIZ',
                vK: 0x7f9,
                vL: '8Ys%',
                vM: 0x2d6,
                vN: 0x1479,
                vO: 0x13f9,
                vP: 'M5Ii',
                vQ: 0x10ce,
                vR: 0x137d,
                vS: 0x174d,
                vT: 0xbc9,
                vU: 'dZbH',
                vV: 'GzjL',
                vW: 0x400,
                vX: '2#Qk',
                vY: 0x834,
                vZ: '$BSl',
                w0: 0x516,
                w1: '6UCx',
                w2: 0x13f5,
                w3: 'dZbH',
                w4: '8Ys%',
                w5: 0x1a92,
                w6: 0x503,
                w7: 'w(Wr',
                w8: 0x155f,
                w9: 0x2da,
                wa: 0xf18,
                wb: 0xe5e,
                wc: 0x98e,
                wd: '9rQu',
                we: 0x17e2,
                wf: 0x190a,
                wg: 'GzjL',
                wh: 0xfc7,
                wi: 0x1140,
                wj: '$p[^',
                wk: '5M6D',
                wl: 0x14d0,
                wm: 'wCGK',
                wn: 0x1e3,
                wo: 0x10d0,
                wp: 0x14de,
                wq: 0x80e,
                wr: 0x1b40,
                ws: 'Gn7Q',
                wt: '9rQu',
                wu: 0xc12,
                wv: 0x48a,
                ww: 0x11ea,
                wx: 0x631,
                wy: '#sM9',
                wz: 0x9d5,
                wA: 0x7b9,
                wB: 0x1347,
                wC: 0x1499,
                wD: 0x1808,
                wE: 0x1f0d,
                wF: 0x15bf,
                wG: 'GzjL',
                wH: 0x17e3,
                wI: 0x1e81,
                wJ: 0x5b4,
                wK: 'XITC',
                wL: 0x120f,
                wM: 0x12a9,
                wN: '8Ys%',
                wO: 'IcEg',
                wP: 0xea1,
                wQ: '8Ys%',
                wR: 0x64b,
                wS: 0xab8,
                wT: 'PYt$',
                wU: 0x1996,
                wV: 'dbGg',
                wW: 0x267,
                wX: 0xb3f,
                wY: 0xaec,
                wZ: '$p[^',
                x0: 0x462,
                x1: 0x196f,
                x2: 'XITC',
                x3: 0x1346,
                x4: 'w(Wr',
                x5: '#sM9',
                x6: 'd%lH',
                x7: '1qbp',
                x8: 0x718,
                x9: 0x9a3,
                xa: '7NO9',
                xb: '6UCx',
                xc: 0x11b6,
                xd: 'GzjL',
                xe: 'jODS',
                xf: 0x1699,
                xg: 0x16a3,
                xh: 0x1a39,
                xi: 0x1edb,
                xj: 0x7eb,
                xk: 0x1834,
                xl: 'dZbH',
                xm: 0x211,
                xn: 'wCGK',
                xo: 0xc9c,
                xp: 0x135,
                xq: 0x5e9,
                xr: 0xc40,
                xs: 0xfec,
                xt: 0xf4d,
                xu: 0x3c9,
                xv: '6UCx',
                xw: '#sM9',
                xx: 'zs!c',
                xy: 0x1063,
                xz: 'dZbH',
                xA: 0xfbd,
                xB: 0x101,
                xC: '$BSl',
                xD: 0x1413,
                xE: 0x8ec,
                xF: 0xf36,
                xG: 0x1ef4,
                xH: '8Ys%',
                xI: 0xf48,
                xJ: 0x8a6,
                xK: 'zs!c',
                xL: 0x1029,
                xM: 'IcEg',
                xN: 0x2fc,
                xO: 0x11bb,
                xP: 0xf34,
                xQ: 0x64a,
                xR: 0x7e1,
                xS: '6UCx',
                xT: 0x831,
                xU: 0x1522,
                xV: '#sM9',
                xW: 'wCGK',
                xX: 0x1c01,
                xY: 'C2T0',
                xZ: 0x19bd,
                y0: 'Pt3!',
                y1: 0x12b9,
                y2: 'rsIZ',
                y3: 0x12d8,
                y4: 0xb6e,
                y5: 0x1816,
                y6: 0x2e3,
                y7: '6UCx',
                y8: 0x1aa2,
                y9: 'Pt3!',
                ya: 0x2e4,
                yb: 'V#kN',
                yc: 0xa19,
                yd: 'IcEg',
                ye: '%oj0',
                yf: 0x1e38,
                yg: 'yxI7',
                yh: 0xe60,
                yi: 0x5e2,
                yj: 0x149,
                yk: '[]Y1',
                yl: 0x37d,
                ym: '89Hn',
                yn: 0x129b,
                yo: 0x821,
                yp: 0xb1d,
                yq: 'GzjL',
                yr: 0x1dfe,
                ys: 0x1af5,
                yt: 0x89c,
                yu: '6UCx',
                yv: 0x4a5,
                yw: 0xbf2,
                yx: 0x1441,
                yy: 'w3Tt',
                yz: 0x1816,
                yA: 0x538,
                yB: 'V#kN',
                yC: 0xd89,
                yD: 0xa9f,
                yE: 0x111f,
                yF: 0xbda,
                yG: 0x11c,
                yH: 0x1ce2,
                yI: 'w(Wr',
                yJ: 0x4c6,
                yK: 'IcEg',
                yL: 0xc24,
                yM: 0x415,
                yN: 0x1d60,
                yO: 'Gn7Q',
                yP: '6UCx',
                yQ: 'w(Wr',
                yR: 0xb6f,
                yS: 0x450,
                yT: 0xcb5,
                yU: '[p9(',
                yV: 0x1757,
                yW: 'ZgMu',
                yX: 0x8ed,
                yY: 'vel(',
                yZ: 0x539,
                z0: 'jODS',
                z1: 0x2f1,
                z2: 0x1d72,
                z3: '5M6D',
                z4: 0x18b5,
                z5: 'XITC',
                z6: 0x1a2,
                z7: 0x309,
                z8: '$BSl',
                z9: 0xbb4,
                za: 'T3Fv',
                zb: 'rsIZ',
                zc: 0x1943,
                zd: 0xbed,
                ze: 'XITC',
                zf: 0x20a,
                zg: 0x19a4,
                zh: 'egod',
                zi: 0x56e,
                zj: 'vel(',
                zk: 0x1d57,
                zl: 0xb37,
                zm: 0x12a0,
                zn: '[p9(',
                zo: 0x1c53,
                zp: 0x10d6,
                zq: 0x1d92,
                zr: 0x7c0,
                zs: 0x9bf,
                zt: '89Hn',
                zu: 'zs!c',
                zv: 0x969,
                zw: 0x155a,
                zx: 0x9bf,
                zy: 0xae2,
                zz: 0xfc7,
                zA: 'Mmsl',
                zB: 0xceb,
                zC: 'PSkb',
                zD: 0x1a4c,
                zE: 0x1bd3,
                zF: 0x1db1,
                zG: '1qbp',
                zH: 0x167b,
                zI: 0x1d91,
                zJ: 0x10c7,
                zK: 0x1d05,
                zL: 'T3Fv',
                zM: 0x108a,
                zN: 'PYt$',
                zO: 'M5Ii',
                zP: 0xe1f,
                zQ: 'dbGg',
                zR: 'oeP*',
                zS: 0x9c9,
                zT: 0xef7,
                zU: 0xb44,
                zV: 0x1649,
                zW: 0xd87,
                zX: 0xde1,
                zY: 'w3Tt',
                zZ: 0x11fa,
                A0: 0x1cb7,
                A1: '$BSl',
                A2: 'dbGg',
                A3: 0xbf2,
                A4: 0x9b6,
                A5: 0x1f05,
                A6: 0x839,
                A7: 0x1ae,
                A8: '#sM9',
                A9: 0x1e1f,
                Aa: 0x106b,
                Ab: 'dbGg',
                Ac: 'oeP*',
                Ad: 0x11ae,
                Ae: '9rQu',
                Af: 0x89e,
                Ag: 0x606,
                Ah: 0x69c,
                Ai: 'yxI7',
                Aj: 0x1ca7,
                Ak: 0xf19,
                Al: 'Pt3!',
                Am: 0x1552,
                An: 0xbfa,
                Ao: 'b)3q',
                Ap: 0x1b06,
                Aq: 0xe68,
                Ar: 0x1d93,
                As: 0xeed,
                At: 'yxI7',
                Au: 'Gn7Q',
                Av: 0x10b1,
                Aw: 'w(Wr',
                Ax: 0x2a6,
                Ay: 0x915,
                Az: 0x74b,
                AA: 0xf49,
                AB: 0x10e1,
                AC: 0x1268,
                AD: 0x5da,
                AE: 'b)3q',
                AF: 0x524,
                AG: 0xb9b,
                AH: 0x805,
                AI: 0xd3e,
                AJ: 0xa1a,
                AK: 'ZgMu',
                AL: 0x1817,
                AM: 0xeda,
                AN: 'C2T0',
                AO: 0x73d,
                AP: 'w(Wr',
                AQ: '0Ua@',
                AR: 0xf29,
                AS: 0x1451,
                AT: 0x284,
                AU: 0x1d4c,
                AV: 'yxI7',
                AW: 0x10bf,
                AX: 'n7E3',
                AY: '[]Y1',
                AZ: 0x1802,
                B0: 0xddf,
                B1: 'egod',
                B2: 0x1c17,
                B3: 'dn8p',
                B4: 0xfac,
                B5: 0x10c2,
                B6: '5M6D',
                B7: 0x1c00,
                B8: 'GzjL',
                B9: 0xb8a,
                Ba: 0x313,
                Bb: 0x169a,
                Bc: 'Mmsl',
                Bd: '[p9(',
                Be: 0x7a7,
                Bf: 'mRB^',
                Bg: 0xde0,
                Bh: 'zs!c',
                Bi: 'ZgMu',
                Bj: 0x1ad9,
                Bk: 0x108e,
                Bl: 'yxI7',
                Bm: 0x1970,
                Bn: 'vel(',
                Bo: 0x1e9a,
                Bp: 0x16c1,
                Bq: 'dZbH',
                Br: 0x49d,
                Bs: 0x1d63,
                Bt: 0xfac,
                Bu: 0x723,
                Bv: 0x66b,
                Bw: '#sM9',
                Bx: 0x7c5,
                By: 0x1ba7,
                Bz: 0x1594,
                BA: 0x6e4,
                BB: 0x966,
                BC: 0x1334,
                BD: 'ZgMu',
                BE: 0x401,
                BF: 'NMJQ',
                BG: 0x1db6,
                BH: 0xea7,
                BI: 0xcab,
                BJ: 'oeP*',
                BK: 0x1394,
                BL: 0x1267,
                BM: 0x153b,
                BN: 0xf1b,
                BO: 0x2ef,
                BP: 'n7E3',
                BQ: 0x1aba,
                BR: 0x1b82,
                BS: 0x1626,
                BT: 'wCGK',
                BU: 'PSkb',
                BV: 0xc97,
                BW: 0x2c3
            },
            mR = { c: 0x1348, f: '*lLT', g: 0x1a16, h: '8Ys%', i: 0x1526 },
            mP = { c: 0xa12 },
            mO = { c: '*lLT', f: '8Ys%', g: 0x7d4, h: 'b)3q', i: 0x19b6, j: 'wCGK', k: 'yxI7', l: 0x1179, m: 'oeP*', n: 0x631, o: '#sM9', p: 0x13de, q: 'dZbH', r: 0x1787, s: '$p[^', t: 0xc16, u: '8Ys%', v: 'jODS', w: 0x1104, x: '9rQu', y: 0x16e1, z: 'dbGg', A: 0xcae, B: '[]Y1', C: 'GzjL', D: 'dn8p', E: '6UCx', F: 0xbe5, G: 'dbGg', H: 0x2db, I: 'M5Ii', J: 0xa37, K: 0x97e, L: '[p9(', M: '5M6D', N: 0x19db, O: 'Pt3!', P: 0x67f, Q: 'w3Tt', R: 0x1ab0, S: 0x58f, T: 0x5da, U: 'Mmsl', V: 0x11cc, W: 'zs!c', X: 'zs!c', Y: 0x1bc1, Z: 0x6c8, a0: 0x1c3a, a1: '89Hn', a2: 'CeJW', a3: 0x9f1, a4: 0x19ae, a5: 0x204, a6: 0xdfa, a7: 'dZbH', a8: 0x947, a9: 0x1a38, aa: 0x1651, ab: 0x1d8e, ac: 0x179f, ad: 0x1a2c, ae: 0x11a1, af: 'dn8p' },
            mN = { c: 0x11d6 },
            g4 = fX;
            const fX = b;
(function(c, f) {
    const mF = {
        c: 0x9c7,
        f: 0xdf7,
        g: 'NMJQ',
        h: 'Gn7Q',
        i: 0x14f2,
        j: 'XITC',
        k: '89Hn',
        l: 0x1673,
        m: 0xec2,
        n: 'yxI7',
        o: 0x13b5,
        p: 'wCGK',
        q: 0x8ef,
        r: 0x1511,
        s: 0xc8b,
        t: 0x1835
    },
    fW = b,
    g = c();
    while (!![]) {
        try {
            const h = -parseInt(fW(mF.c, 'IcEg')) / 0x1 * (parseInt(fW(mF.f, mF.g)) / 0x2) + parseInt(fW(0x1929, mF.h)) / 0x3 * (-parseInt(fW(mF.i, mF.j)) / 0x4) + -parseInt(fW(0xe11, mF.k)) / 0x5 + -parseInt(fW(mF.l, 'd%lH')) / 0x6 * (-parseInt(fW(mF.m, mF.n)) / 0x7) + -parseInt(fW(mF.o, mF.p)) / 0x8 + -parseInt(fW(mF.q, '9rQu')) / 0x9 * (-parseInt(fW(mF.r, '7NO9')) / 0xa) + parseInt(fW(mF.s, 'Mmsl')) / 0xb * (parseInt(fW(mF.t, 'n7E3')) / 0xc);
            if (h === f) break;
            else g['push'](g['shift']());
        } catch (i) {
            g['push'](g['shift']());
        }
    }
}(a, 0x1d218));

let cfSocketConnect = null;
try {
    import(fX(0x1b57, 'T3Fv'))[fX(0x1600, 'zs!c')](c => {
        const mG = { c: 'NxG1', f: 'vel(' },
        fY = fX;
        if (c && typeof c[fY(0x6b1, mG.c)] === fY(0x8d2, '*lLT')) cfSocketConnect = c[fY(0x1dc0, mG.f)];
    })[fX(0x9c6, 'yxI7')](() => {});
} catch (d) {}

const Version = fX(0x900, 'dZbH');
let config_JSON, proxyIP = '',
    enableSocks5Proxy = null,
    enableSocks5GlobalProxy = ![],
    mySocks5Account = '',
    parsedSocks5Address = {},
    cachedSocks5Whitelist = null,
    cachedProxyIP,
    cachedProxyResolvedArray,
    cachedProxyArrayIndex = 0x0,
    enableProxyFallback = !![],
    debugLogPrint = ![],
    connProxyWhitelist = [];

function hostMatchesProxyList(c) {
    const mJ = { c: 0xfba, f: '9rQu' },
    mI = { c: 0xa8b, f: 'egod', g: 0x16e1, h: '2#Qk' },
    fZ = fX,
    f = connProxyWhitelist[fZ(0x1ea4, 'XITC')] ? SOCKS5whitelist[fZ(mJ.c, mJ.f)](connProxyWhitelist) : SOCKS5whitelist;
    return f[fZ(0x1095, '6UCx')](g => {
        const g0 = fZ;
        try {
            return new RegExp('^' + String(g)[g0(mI.c, 'vel(')]()[g0(0xa43, mI.f)](/\*/g, '.*') + '$', 'i')[g0(mI.g, mI.h)](c);
        } catch (h) {
            return ![];
        }
    });
}
let nat64Config = '',
    cachedNat64Prefixes = null,
    cachedNat64At = 0x0,
    cachedNat64Src = '',
    networkSettings = null,
    cachedNetworkSettings = null,
    cachedNetworkSettingsAt = 0x0,
    cachedAdminPass = null,
    cachedAdminPassAt = 0x0;
const _CFG_KEY = fX(0xffc, 'ZgMu');
let _cfgRaw = null,
    _cfgRawAt = 0x0;

async function getConfigRaw(c) {
    const mK = { c: 'CeJW', f: 0x16c4 },
    g1 = fX;
    if (_cfgRaw !== null && Date[g1(0x1d80, 'egod')]() - _cfgRawAt < 0x7530) return _cfgRaw;
    try {
        _cfgRaw = c['KV'] && typeof c['KV'][g1(0x14be, mK.c)] === g1(mK.f, '[p9(') ? await c['KV'][g1(0xb3b, 'NMJQ')](_CFG_KEY) : null;
        _cfgRawAt = Date[g1(0xecf, '60r9')]();
    } catch (f) {}
    return _cfgRaw;
}

function putConfig(c, f) {
    const mL = { c: 0x1ee2 },
    g2 = fX;
    return _cfgRaw = f, _cfgRawAt = Date[g2(0x1af6, '9rQu')](), c['KV'][g2(mL.c, 'w(Wr')](_CFG_KEY, f);
}
let cachedWorkerUUID = null,
    cachedWorkerUUIDAt = 0x0,
    savedUsersAuth = null,
    savedUsersAuthAt = 0x0,
    lastCentralSync = 0x0,
    SOCKS5whitelist = [fX(0x17bf, 'wCGK'), fX(0x122b, 'Pt3!'), fX(0x133d, 'yxI7'), fX(0x207, 'rsIZ'), fX(0xa81, 'jODS')],
    PagesstaticPages = fX(0x17e6, 'rsIZ');
globalThis[fX(0x1107, '6UCx')] = Date[fX(0x7ec, '0Ua@')]();
const SESSION_MAX_AGE_MS = 0x5265c00,
    LOGIN_MAX_ATTEMPTS = 0x8,
    LOGIN_WINDOW_MS = 0x927c0,
    LOGIN_BLOCK_MS = 0xdbba0,
    __loginAttempts = new Map(),
    WSearlyDataMaxBytes = 0x8 * 0x400,
    WSearlyDataMaxHeaderLength = Math[fX(0x1d23, 'vel(')](WSearlyDataMaxBytes * 0x4 / 0x3) + 0x4,
    upstreamBatchTargetBytes = 0x40 * 0x400,
    upstreamQueueMaxBytes = 0x20 * 0x400 * 0x400,
    upstreamQueueMaxItems = 0x2000,
    downstreamGrainChunkBytes = 0x40 * 0x400,
    downstreamGrainTailThreshold = 0x200,
    downstreamGrainSilentMs = 0x0,
    TCPconcurrentDialCount = 0x4,
    uuidRegex = /^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-4[0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$/,
    NODE_ADDR_REGEX = /^(\[[\da-fA-F:]+\]|[\d.]+|[a-zA-Z0-9](?:[a-zA-Z0-9-]*[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]*[a-zA-Z0-9])?)*)(?::(\d+))?(?:#(.+))?$/,
    TAAKAA_REPO_RAW = fX(0x1032, '*lLT'),
    TAAKAA_VERSION_URL = TAAKAA_REPO_RAW + fX(0x912, 'wCGK'),
    TAAKAA_WORKER_SRC_FALLBACK = TAAKAA_REPO_RAW + fX(0x27b, '9rQu');

function versionGreater(c, f) {
    const mM = { c: '*lLT', f: 0x14de, g: 0x1c8d, h: 0x1b72, i: 0x272, j: 'b)3q', k: 0x1de2, l: '2#Qk', m: 'M5Ii', n: 0xfd3 },
    g3 = fX,
    g = String(c || '')[g3(0x5da, 'Mmsl')](/^[vV]/,'')[g3(0x1df, mM.c)]('.')[g3(mM.f, '9rQu')](j => parseInt(j, 0xa) || 0x0),
    h = String(f || '')[g3(mM.g, 'dbGg')](/^[vV]/,'')[g3(mM.h, 'n7E3')]('.')[g3(mM.i, mM.j)](j => parseInt(j, 0xa) || 0x0);
    for (let j = 0x0; j < Math[g3(mM.k, mM.l)](g[g3(0x1d2d, mM.m)], h[g3(mM.n, 'Mmsl')]); j++) {
        const k = g[j] || 0x0,
            l = h[j] || 0x0;
        if (k > l) return !![];
        if (k < l) return ![];
    }
    return ![];
}
            
